<a href="https://colab.research.google.com/github/Swathi12499/DataAnalytics/blob/master/ANNLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Keras is a deep learning framework to build neural networks

from keras.models import Sequential #to create model layer by layer
from keras.layers import Dense #to create fully connected network
import numpy as np

Using TensorFlow backend.


In [0]:
from sklearn.datasets import load_iris #to load the standard iris dataset
#Standard Scaler to standardize(z score) the data by making zero mean and unit variance
#One hot encoder  to give a binary representation
from sklearn.preprocessing import StandardScaler,OneHotEncoder 
from sklearn.model_selection import train_test_split # to split data for training and testing

In [0]:
iris = load_iris() # loads the iris dataset

In [7]:
print(iris.feature_names) #prints the various features
print(iris.target_names) #prints the target classes
print(iris.DESCR) # prints description of attributes and the dataset


['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high

In [9]:
print(iris.data) 

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [0]:
input_data = iris.data

In [17]:
target_class = iris.target
print(target_class)
print(target_class.shape)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
(150,)


Performing the Z score Normalisation using Standard Scaler

In [0]:
scaler = StandardScaler()
#fit calculates mean and variance and then transforms input data to zero mean and unit variance
input_scaled = scaler.fit_transform(input_data) 

In [18]:
#  the categorial attributes in the target class are converted into binary values 
enc = OneHotEncoder()
hot_target_class = enc.fit_transform(target_class[:, np.newaxis]).toarray()
print(hot_target_class)
print(hot_target_class.shape)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [0]:
x_train,x_test,y_train,y_test = train_test_split(input_scaled,hot_target_class,test_size=0.3) #splitting dataset in the ratio 70:30 for train and test respectively
#x_train
#x_test

In [20]:
model = Sequential()

W0820 06:06:47.296436 140326192584576 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.



In [21]:
h1 = model.add(Dense(6,activation="relu",input_dim=4)) #6 neurons in first hidden layer , with relu activation function is added
h2=model.add(Dense(5,activation="relu"))
h3=model.add(Dense(7,activation="relu"))
o = model.add(Dense(3,activation="softmax")) # 3 neuron output layer and uses softmax activation function



W0820 06:07:47.399413 140326192584576 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0820 06:07:47.415045 140326192584576 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.



In [22]:
model.compile(loss="categorical_crossentropy",optimizer="Adam",metrics=['accuracy'])

W0820 06:15:19.657790 140326192584576 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0820 06:15:19.701419 140326192584576 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3295: The name tf.log is deprecated. Please use tf.math.log instead.



In [23]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 6)                 30        
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 35        
_________________________________________________________________
dense_3 (Dense)              (None, 7)                 42        
_________________________________________________________________
dense_4 (Dense)              (None, 3)                 24        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


In [24]:
model.fit(x_train,y_train,batch_size=10,epochs=50)

W0820 06:16:12.224343 140326192584576 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0820 06:16:12.288005 140326192584576 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.



Epoch 1/50
105/105 [==============================] - 1s 7ms/step - loss: 1.0547 - acc: 0.4095
Epoch 2/50
105/105 [==============================] - 0s 156us/step - loss: 1.0189 - acc: 0.5619
Epoch 3/50
105/105 [==============================] - 0s 172us/step - loss: 0.9834 - acc: 0.6571
Epoch 4/50
105/105 [==============================] - 0s 166us/step - loss: 0.9506 - acc: 0.7048
Epoch 5/50
105/105 [==============================] - 0s 142us/step - loss: 0.9193 - acc: 0.7143
Epoch 6/50
105/105 [==============================] - 0s 153us/step - loss: 0.8903 - acc: 0.7524
Epoch 7/50
105/105 [==============================] - 0s 195us/step - loss: 0.8608 - acc: 0.7619
Epoch 8/50
105/105 [==============================] - 0s 186us/step - loss: 0.8351 - acc: 0.7810
Epoch 9/50
105/105 [==============================] - 0s 155us/step - loss: 0.8085 - acc: 0.7905
Epoch 10/50
105/105 [==============================] - 0s 154us/step - loss: 0.7818 - acc: 0.7524
Epoch 11/50
105/105 [==========

In [25]:
 score = model.evaluate(x_test,y_test, verbose=0)
 print('Test loss:', score[0])
 print('Test accuracy:', score[1])

Test loss: 0.19089990788035924
Test accuracy: 0.9777777777777777
